program SysEgg;

uses
  windows,
  Forms,
  Base in 'Base.pas' {DmDados: TDataModule},
  UCadastroUnidades in 'UCadastroUnidades.pas' {FrmCadastroUnidades},
  UVendedores in 'UVendedores.pas' {FrmVendedores},
  UFornecedores in 'UFornecedores.pas' {Fmfornecedores},
  UProdutos in 'UProdutos.pas' {FmProdutos},
  URelOrcamento in 'URelOrcamento.pas' {QrOrcamento: TQuickRep},
  URelClientes in 'URelClientes.pas' {QrCliente: TQuickRep},
  URelFornecedores in 'URelFornecedores.pas' {QrFornecedores: TQuickRep},
  UQrLabelCliente in 'UQrLabelCliente.pas' {QRLabelFormCliente},
  UQrLabelFornecedor in 'UQrLabelFornecedor.pas' {QRLabelFormFornecedore},
  UGraficos in 'UGraficos.pas' {FmGraficos},
  Ufunctions in 'Ufunctions.pas',
  UAbertura in 'UAbertura.pas' {SplashForm},
  UDMUsuario in 'UDMUsuario.pas' {DMSenha: TDataModule},
  Ucic_cgc in 'Ucic_cgc.pas' {fciccgc},
  UPesquisaProdutoparaVendas in 'UPesquisaProdutoparaVendas.pas' {FrmPesquisaProduto},
  UConsultaProduto in 'UConsultaProduto.pas' {ConsultaProduto},
  URelProdutos in 'URelProdutos.pas' {FrmRelProdutos},
  UFaturamento in 'UFaturamento.pas' {FrmFaturamento},
  URelLucros in 'URelLucros.pas' {FrmRelLucros},
  UFrmNecessidadedeCompra in 'UFrmNecessidadedeCompra.pas' {FrmNecessidadedeCompras},
  UFrmRelNecessidadeCompras in 'UFrmRelNecessidadeCompras.pas' {FrmRelNecessidadeCompras},
  UFrmConsultaFornecedor in 'UFrmConsultaFornecedor.pas' {FrmProcuraporNomeFornecedor},
  UFrmConsultaVendedor in 'UFrmConsultaVendedor.pas' {FrmConsultaVendedor},
  UPesquisaNomeCliente in 'UPesquisaNomeCliente.pas' {FrmPequisaClienteVendas},
  UMain in 'UMain.pas' {FrmMain},
  UFrmPermissoes in 'UFrmPermissoes.pas' {FrmControledePermissoes},
  UFormAniversario in 'UFormAniversario.pas' {frmAniversariantes},
  ULogin in 'ULogin.pas' {FrmLogin},
  URelatorioDespesas in 'URelatorioDespesas.pas' {FrmRelatorioDespesas},
  UCalculadora in 'UCalculadora.Pas' {FormCalculadora},
  URelAniversariantes in 'URelAniversariantes.pas' {FrmConsultaAniversariantes},
  URelatoriodeDespesas in 'URelatoriodeDespesas.pas' {FrmRelatoriodeDespesas},
  UCalendario_legal in 'UCalendario_legal.pas' {F_Calendario},
  Interno in 'Interno.Pas',
  UConfiguracoes in 'UConfiguracoes.pas' {FormDadosEmpresa},
  UFrmFormasPagamento in 'UFrmFormasPagamento.pas' {FrmCadastroFormasPagamento},
  UProcuraNomeClientePedido in 'UProcuraNomeClientePedido.pas' {FrmProcuraNomeClientePedido},
  UProcuraporClienteouPedido in 'UProcuraporClienteouPedido.pas' {FrmProcuraporClienteouPedido},
  UProcuraVendedor in 'UProcuraVendedor.pas' {FrmProcuraVendedor},
  UCadClie in 'UCadClie.pas' {FrmCadClie},
  UCadstrodeFuncionarios in 'UCadstrodeFuncionarios.pas' {FrmCadastrodeFuncionarios},
  UCadastrodeCombustivel in 'UCadastrodeCombustivel.pas' {FrmCadastrodeCombustivel},
  UPedidos in 'UPedidos.pas' {FmPedidos},
  UPesquisaFornecedorparaProduto in 'UPesquisaFornecedorparaProduto.pas' {FrmPesquisaFornecedor},
  UCalculoComissoporVendedores in 'UCalculoComissoporVendedores.pas' {FrmCalculoComissaoporVendedores},
  UProcuraVendedorComissao in 'UProcuraVendedorComissao.pas' {FrmProcuraVendedorComissao},
  UCalculoComissoVendedoresTodos in 'UCalculoComissoVendedoresTodos.pas' {FrmCalculoComissaoVendedoresTodos},
  URelComissaoTodos in 'URelComissaoTodos.pas' {FrmRelatorioComissaoTodos},
  URelComissaoporVendedor in 'URelComissaoporVendedor.pas' {FrmRelatorioComissaoporVendedor},
  UCadastrodeDespesas in 'UCadastrodeDespesas.pas' {FrmCadastrodeDespesas},
  URelVendedorXClientes in 'URelVendedorXClientes.pas' {FrmRelVendedorXClientes},
  URelClientesXPedidos in 'URelClientesXPedidos.pas' {FrmRelClienterXPedidos},
  UConsultaFaturamento in 'UConsultaFaturamento.pas' {FrmConsultaFaturamento},
  UConsultaDespesas in 'UConsultaDespesas.pas' {FrmConsultaDespesas},
  UConsultaComissoes in 'UConsultaComissoes.pas' {FrmConsultaComissoes},
  URelLevantamentodeEstoque in 'URelLevantamentodeEstoque.pas' {FrmRelLevantamentodeEstoque},
  URelFornecedorXProdutos in 'URelFornecedorXProdutos.pas' {FrmRelFornecedorXProdutos},
  UMudarSenha in 'UMudarSenha.pas' {FrmMudarSenha},
  UCadastroEmpresas in 'UCadastroEmpresas.pas' {FrmCadastrodeEmpresas},
  URelComissoesVendedoresSintetico in 'URelComissoesVendedoresSintetico.pas' {FrmRelComissoesVendSintetico},
  UConsultaComissoesVendedoresSintetico in 'UConsultaComissoesVendedoresSintetico.pas' {FrmConsultaComissoesVendedoresSintetico},
  UConsultaTotalizacoesProduto in 'UConsultaTotalizacoesProduto.pas' {FrmConsultaTotalProdutos},
  URankingVendasdeProdutos in 'URankingVendasdeProdutos.pas' {FrmRankingvendasdeProdutos},
  UFaturados in 'UFaturados.pas' {FrmFaturados},
  URankingClientes in 'URankingClientes.pas' {FrmRankingClientes},
  URelRankingProdutos in 'URelRankingProdutos.pas' {FrmRelRankingProdutos},
  UAboutMydas in 'UAboutMydas.pas' {AboutBoxMydas},
  UCadastroEmbalagens in 'UCadastroEmbalagens.pas' {FrmCadastroEmbalagens},
  UControleComprasProdutos in 'UControleComprasProdutos.pas' {FrmControleComprasProdutos},
  URelacaoClientesporDiaSemana in 'URelacaoClientesporDiaSemana.pas' {FrmRelacaoClientesporDiaSemana},
  URelClientesporSemana in 'URelClientesporSemana.pas' {FrmRelClientesporSemana},
  UConsultaEstoque in 'UConsultaEstoque.pas' {FrmConsultaEstoque},
  UConsultadeFaturadosPendentes in 'UConsultadeFaturadosPendentes.pas' {FrmConsultadeFaturadosPendentes},
  URelDespesas in 'URelDespesas.pas' {FrmRelDespesas},
  URelFaturadosPendentes in 'URelFaturadosPendentes.pas' {FrmRelFaturadosPendentes},
  UVendasnoBalcao in 'UVendasnoBalcao.pas' {FmVendasBalcao},
  UConsultaProdutoVendasBalcao in 'UConsultaProdutoVendasBalcao.pas' {FrmConsultaProdutoVendasBalcao},
  Extens in 'Extens.pas',
  UProcuraBoleto in 'UProcuraBoleto.pas' {FrmProcurarBoleto},
  UConsultaVendasExternas in 'UConsultaVendasExternas.pas' {FrmConsultaVendasExternas},
  URelatorioVendasExternas in 'URelatorioVendasExternas.pas' {FrmRelatorioVendasExternas},
  UConsultaClientesparaVendasExternas in 'UConsultaClientesparaVendasExternas.pas' {FrmConsultaClienteVendasExternas},
  UConsultaVendaBalcao in 'UConsultaVendaBalcao.pas' {FrmConsultaVendaBalcao},
  URelatorioVendasBalcao in 'URelatorioVendasBalcao.pas' {FrmRelatorioVendasBalcao},
  UTabeladePrecosBalcao in 'UTabeladePrecosBalcao.pas' {FrmTabeladePrecosBalcao},
  UConsultaEstoqueEmbalagens in 'UConsultaEstoqueEmbalagens.pas' {FrmConsultaEstoqueEmbalagens},
  UConsultadeComprasEfetuadas in 'UConsultadeComprasEfetuadas.pas' {FrmConsultaComprasEfetuadas},
  UConsultadeVendas in 'UConsultadeVendas.pas' {FrmConsultadeVendas},
  UContasaPagar in 'UContasaPagar.pas' {FrmContasapagar},
  URelatorioContasapagar in 'URelatorioContasapagar.pas' {FrmRelatorioContasaPagar},
  USenhaAcessoGerencial in 'USenhaAcessoGerencial.pas' {FrmSenhadeAcessoGerencial},
  UFluxodeCaixa in 'UFluxodeCaixa.pas' {FrmFluxodeCaixa},
  URelFluxodeCaixaNew in 'URelFluxodeCaixaNew.pas' {QrFluxoCaixa: TQuickRep},
  URelComprasEfetuadas in 'URelComprasEfetuadas.pas' {FrmRelComprasEfetuadas},
  UConsutltaAtivoPassivo in 'UConsutltaAtivoPassivo.pas' {FrmConsultaAtivoPassivo},
  UPesquisaCheque in 'UPesquisaCheque.pas' {FrmPesquisaCheque},
  UCalculoFaturamentoPerodo in 'UCalculoFaturamentoPerodo.pas' {FrmCalculoFaturamentoPeriodo},
  UConsultaItensVendidos in 'UConsultaItensVendidos.pas' {FrmConsultaItensVendidos},
  UConsultaHistoricodeCompras in 'UConsultaHistoricodeCompras.pas' {FrmConsultadeHistoricodeCompras},
  Rotina in 'Rotina.pas',
  UConsultaVendasBalcao in 'UConsultaVendasBalcao.pas' {FrmConsultaVendasBalcao},
  UListaPedidos in 'UListaPedidos.pas' {FormListadePedidos},
  UContasaReceberNew in 'UContasaReceberNew.pas' {FrmContasaReceberNew},
  UConsultaProdutosCadastrados in 'UConsultaProdutosCadastrados.pas' {FrmConsultaProdutosCadastrados},
  UEstoque in 'UEstoque.pas' {FrmEstoque},
  UContasaPagarNew in 'UContasaPagarNew.pas' {FrmContasaPagarNew},
  UConsultaContasPagar in 'UConsultaContasPagar.pas' {FrmConsultaContasPagar},
  UConsultaContasReceber in 'UConsultaContasReceber.pas' {FrmConsultaContasReceber},
  UCadastroFormasPagamentoNew in 'UCadastroFormasPagamentoNew.pas' {FrmCadFormasPagamentoNew},
  UConsultaClientesFormaPagto in 'UConsultaClientesFormaPagto.pas' {FrmConsultaClientesFormaPagto},
  u_parcelamento in 'u_parcelamento.pas' {FrmGerarParcelamentos},
  USuporte in 'USuporte.pas' {FrmSuporte},
  UEntradadeProduto in 'UEntradadeProduto.pas' {FrmEntradaProduto},
  URelatorioContasPagar in 'URelatorioContasPagar.pas' {frmRelContasPagar},
  URelContasPagar in 'URelContasPagar.pas' {FrmRelatorioContasPagar},
  UCadastroTipoEntrada in 'UCadastroTipoEntrada.pas' {FrmCadastroTipoEntrada},
  UCadastroTipoSaida in 'UCadastroTipoSaida.pas' {FrmCadastroTipoSaida},
  UFrmRelatorioContasReceber in 'UFrmRelatorioContasReceber.pas' {FrmRelatorioContasReceber},
  URelatorioContasReceber in 'URelatorioContasReceber.pas' {RelatorioContasReceber},
  URelEstoque in 'URelEstoque.pas' {FrmRelatorioEstoque},
  UAtualizaQtdOvo in 'UAtualizaQtdOvo.pas' {FrmAtualizaQtdOvo},
  RelatorioVendasAgrupadas in 'RelatorioVendasAgrupadas.pas' {frmGrouping},
  URelatorioVendasAgrupadasNovo in 'URelatorioVendasAgrupadasNovo.pas' {FrmRelatorioVendasAgrupadasNovo},
  RelAgrupamentoContasReceber in 'RelAgrupamentoContasReceber.pas' {FrmAgrupamentoContasReceber},
  UCadastrodePerdas in 'UCadastrodePerdas.pas' {FrmCadastrodePerdas},
  UBuscaProdutoPerda in 'UBuscaProdutoPerda.pas' {FrmBuscaProdutoPerda};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'MIDAS SYSTEM';
  Application.Initialize;
//  SplashForm:= TSplashForm.Create(application);
//  SplashForm.Show;
//  SplashForm.Update;
//  Application.CreateForm(TFrmMain, FrmMain);
  Application.CreateForm(TFrmLogin, FrmLogin);
  Application.CreateForm(TFrmMain, FrmMain);
  Application.CreateForm(TDmDados, DmDados);
  Application.CreateForm(TFrmMudarSenha, FrmMudarSenha);
  Application.CreateForm(TFrmConsultaClientesFormaPagto, FrmConsultaClientesFormaPagto);
  Application.CreateForm(TFrmGerarParcelamentos, FrmGerarParcelamentos);
  Application.CreateForm(TFrmConsultaContasPagar, FrmConsultaContasPagar);
  //  Application.CreateForm(TFrmAnivClientes, FrmAnivClientes);
  Application.Run;
end.


